String code = "";
String tempostr = "";
int tempo = 0;
float tempof = 0;
float beat = 0;
int beatint = 0;
int pulse_width = 300;
int togglePin = 8;
int togglePin2 = 13;
int count;
int repeats = 5;
int length = 0;
int i = 0;
int d = 25;
int off = 200;
String wordle = "";
void setup() {
  pinMode(togglePin,OUTPUT);
  pinMode(togglePin2, OUTPUT);
  digitalWrite(togglePin2,LOW);
  digitalWrite(togglePin,LOW);
	Serial.begin(115200);
}
void loop() {
  listen();
  Serial.print(wordle);
  for(i = 0;i<length;i++){
    if(wordle.substring(i,i+1)=="a"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
    }
    else if(wordle.substring(i,i+1)=="b"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }
     else if(wordle.substring(i,i+1)=="c"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off); 
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="d"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="e"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="f"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="g"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="h"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
  }else if(wordle.substring(i,i+1)=="i"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="j"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="k"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="l"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="m"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
    }else if(wordle.substring(i,i+1)=="n"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
    }else if(wordle.substring(i,i+1)=="o"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="p"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="q"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="r"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="s"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }
    else if(wordle.substring(i,i+1)=="t"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="u"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off); 
    }else if(wordle.substring(i,i+1)=="v"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="w"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="x"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="y"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }else if(wordle.substring(i,i+1)=="z"){
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(2*d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
      digitalWrite(togglePin,HIGH);
      delay(d);
      digitalWrite(togglePin,LOW);
      delay(off);
    }
    delay(2000);
  }
}
void listen(){
  while (!Serial.available());
    code = Serial.readString();
    length = code.substring(0,1).toInt();
    wordle = code.substring(1,1+length);
    wordle = wordle.substring(0,length);

    
}